const InstituteNames = [
  "Indian Institute of Technology, Bombay",
  "Indian Institute of Technology, Delhi",
  "Indian Institute of Technology, Kharagpur",
  "Indian Institute of Technology, Madras",
  "Indian Institute of Technology, Kanpur",
  "Indian Institute of Technology, Roorkee",
  "Indian Institute of Technology, Guwahati",
  "Indian Institute of Technology, Hyderabad",
  "Indian Institute of Technology, Patna",
  "Indian Institute of Technology, (ISM) Dhanbad",
  "Indian Institute of Technology, Bhubaneswar",
  "Indian Institute of Technology, Gandhinagar",
  "Indian Institute of Technology, Ropar",
  "Indian Institute of Technology, Indore",
  "Indian Institute of Technology, Mandi",
  "Indian Institute of Technology, Jodhpur",
  "Indian Institute of Technology, Tirupati",
  "Indian Institute of Technology, Palakkad",
  "Indian Institute of Technology, Dharwad",
  "Indian Institute of Technology, Bhilai",
  "Indian Institute of Technology, Goa",
  "Indian Institute of Technology, Jammu",
  "Indian Institute of Information Technology, Pune",
  "Indian Institute of Information Technology, Delhi",
  "Indian Institute of Information Technology, Hyderabad",
  "Indian Institute of Information Technology, Bangalore",
  "Indian Institute of Information Technology, Allahabad",
  "Indian Institute of Information Technology, Bhubaneswar",
  "Indian Institute of Information Technology, Vadodara",
  "Indian Institute of Information Technology, Kota",
  "Indian Institute of Information Technology, Guwahati",
  "National Institute of technology Trichy",
  "National Institute of technology Warangal",
  "National Institute of technology Surathkal",
  "National Institute of technology Calicut",
  "National Institute of technology Rourkela",
  "National Institute of technology Kurukshetra",
  "National Institute of technology Durgapur",
  "National Institute of technology Jamshedpur",
  "National Institute of technology Silchar",
  "National Institute of technology Srinagar",
  "National Institute of technology Hamirpur",
  "National Institute of technology Agartala",
  "National Institute of technology Meghalaya",
  "National Institute of technology Nagaland",
  "National Institute of technology Manipur",
  "National Institute of technology Mizoram",
  "Birla Institute of Technology Pilani",
  "Birla Institute of Technology Goa",
  "Birla Institute of Technology Hyderabad",
  "ISM Dhanbad",
  "IISc Bangalore",
  "Indian Institute of Managament Ahmedabad",
  "Indian Institute of Managament Bangalore",
  "Indian Institute of Managament Calcutta",
  "Indian Institute of Managament Lucknow",
  "Indian Institute of Managament Indore",
  "Indian Institute of Managament Kozhikode",
  "Indian Institute of Managament Shillong",
  "Indian Institute of Managament Rohtak",
  "Indian Institute of Managament Trichy",
  "Indian Institute of Managament Udaipur",
  "Indian Institute of Managament Kashipur",
  "Indian Institute of Managament Ranchi",
  "Indian Institute of Managament Nagpur",
  "Indian Institute of Managament Amritsar",
  "Indian Institute of Managament Bodh Gaya",
  "Indian Institute of Managament Jammu",
  "Indian Institute of Managament Sambalpur",
  "Indian Institute of Managament Sirmaur",
  "Indian Institute of Managament Visakhapatnam",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  "IISER Nagaland",
  "IISER Jammu",
  "IISER Gandhinagar",
  "IISER Bhubaneswar",
  "IISER Tirupati",
  "IISER Kochi",
  "IISER Visakhapatnam",
  "IISER Pune",
  "IISER Kolkata",
  "IISER Mohali",
  "IISER Bhopal",
  "IISER Thiruvananthapuram",
  "IISER Tirupati",
  "IISER Berhampur",
  "IISER Nagaland",
  "IISER Jammu",
  "IISER Gandhinagar",
  "IISER Bhubaneswar",
  "IISER Tirupati",
  "IISER Kochi",
  "IISER Visakhapatnam",
  "IIFT Delhi",
  "IIFT Kolkata",
];
const TopicNames = [
  "Transfer Learning",
  "Federated Learning",
  "Reinforcement Learning",
  "Time Series Forecasting",
  "Anomaly Detection",
  "Generative Adversarial Networks (GANs)",
  "Convolutional Neural Networks (CNNs)",
  "Recurrent Neural Networks (RNNs):",
  "Transformer Models",
  "Self-Supervised Learning",
  "Few-Shot Learning",
  "Human-Robot Interaction",
  "Swarm Robotics",
  "Robot Learning from Demonstration (LfD)",
  "Soft Robotics",
  "Edge Computing",
  "Serverless Computing",
  "Multi-Cloud Management",
  "Energy-Efficient Cloud Computing",
  "Software-Defined Networking (SDN)",
  "Network Security",
  "Internet of Things (IoT) Networking",
  "5G and Beyond",
  "Content Delivery Networks (CDNs)",
  "Artificial Intelligence",
  "Automation",
  "Data Science",
  "Natural Language Processing (NLP)",
  "Sentiment Analysis",
  "Speech Recognition and Synthesis",
  "Recommender Systems",
  "Computer Vision",
  "Image Recognition and Classification",
  "Object Detection and Tracking",
  "Emotion Recognition",
  "Gesture Recognition",
  "Augmented Reality (AR)",
  "Virtual Reality (VR)",
  "Mixed Reality (MR)",
  "Autonomous Vehicles",
  "Smart Cities",
  "Blockchain Technology",
  "Cryptocurrency and Digital Payments",
  "Decentralized Finance (DeFi)",
  "Cryptography and Privacy-Preserving Technologies",
  "Cybersecurity and Ethical Hacking",
  "Privacy-Preserving Machine Learning",
  "Social Robotics and Companion Robots",
  "Renewable Energy Systems and Smart Grids",
  "Sustainable Technologies",
  "Environmental Monitoring and Climate Change Analysis",
  "Human-Computer Interaction (HCI)",
  "User Experience (UX) Design",
  "Quantum Computing",
  "Geospatial Analysis",
  "Computational Neuroscience",
  "Brain-Computer Interfaces",
  " Gamification",
  "Machine Learning",
];
export { InstituteNames, TopicNames };
