export const data1 = [
  {
    imgURL: "",
    ResearchArea: "Dementia detection using Machine Learning",
    ProfessorName: "Dr. Rachin Raghav",
    College: "Indian Institute of Technology, Bombay",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "2 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Digital Authentication using CNN",
    ProfessorName: "Dr. Shyam Sachin",
    College: "Indian Institute of Technology, Delhi",
    Topics: ["CNN", "ANN", "SVM"],
    Remote: false,
    Stipend: "10K",
    Duration: "2 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "1 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Deep Fake Detection",
    ProfessorName: "Dr. David Dharam ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "3 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Certificate Generation using Blockchain",
    ProfessorName: "Dr. Romil Jain ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Blockchain", "Solidity", "Cryptocurrency"],
    Remote: false,
    Stipend: "20K",
    Duration: "3 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Fake news detection using Machine learning",
    ProfessorName: "Dr. Ravi Sharma ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "6 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Deep Fake Detection",
    ProfessorName: "Dr. David Dharam ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "3 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
];

export const data2 = [
  {
    imgURL: "",
    ResearchArea: "Dementia detection using Machine Learning",
    ProfessorName: "Dr. Rachin Raghav",
    College: "Indian Institute of Technology, Bombay",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "3 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Digital Authentication using CNN",
    ProfessorName: "Dr. Shyam Sachin",
    College: "Indian Institute of Technology, Delhi",
    Topics: ["CNN", "ANN", "SVM"],
    Remote: false,
    Stipend: "10K",
    Duration: "2 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "1 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Deep Fake Detection",
    ProfessorName: "Dr. David Dharam ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "4 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Certificate Generation using Blockchain",
    ProfessorName: "Dr. Romil Jain ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Blockchain", "Solidity", "Cryptocurrency"],
    Remote: false,
    Stipend: "20K",
    Duration: "2 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Fake news detection using Machine learning",
    ProfessorName: "Dr. Ravi Sharma ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "6 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
  {
    imgURL: "",
    ResearchArea: "Deep Fake Detection",
    ProfessorName: "Dr. David Dharam ",
    College: "Indian Institute of Technology, Kharagpur",
    Topics: ["Computer Vision", "Image Processing", "Keras"],
    Remote: false,
    Stipend: "15K",
    Duration: "3 months",
    Details:
      "https://drive.google.com/file/d/1L3y2NcRbbZrHQqb9BLSlz3MD7NSdtc_7/view?usp=drive_link",
    DayPosted: "2 weeks ago",
    ApplyBy: "2 April 2024",
  },
];
